### ISSUE TITLE
intergrating the gem with middleman

### ISSUE THREAD

**Issue by JoshuaWoodsdev** [datocms/middleman-dato#13]
middleman_dato/middleman_extension.rb:6:in `require': cannot load such file -- dato/watch/site_change_watcher (LoadError)
Is the error that shows up with trying to start the server. After adding Dato to the config.rb file

**Comment by matjack1** [comment]
I've just tried with our starter project here: https://github.com/datocms/middleman-portfolio/ where we integrate the gem with middleman and all works fine. I'm closing for now, but if it's still relevant please reopen with some more details, like gem versions and a config.rb file
