### ISSUE TITLE
Access global settings

### ISSUE THREAD

**Issue by jonlay** [datocms/middleman-dato#2]
Hey guys

I don't believe this is currently possible, or at least it just hasn't been documented. Could you explain how to access DatoCMS data that's inside Content > Settings, using this gem. i.e. this page: `https://xxxx.admin.datocms.com/editor/settings`

I'd propose:

    <%= dato.settings %>

And also that the following helper should generate all the meta settings:

    <%= dato_meta_tags(settings) %>

**Comment by stefanoverna** [comment]
You can access to site settings like this:

```ruby
dato.site.global_seo
dato.site.favicon
dato.site.name
dato.site.locales
```

**Comment by stefanoverna** [comment]
`dato_meta_tags` already uses the site settings to generate SEO metadata

**Comment by jonlay** [comment]
Thanks for your help! I've also done a quick PR to make that clearer in the README for anyone else.
