### ISSUE TITLE
Cant start Middleman 4.0 after activating dato in config.

### ISSUE THREAD

**Issue by meandkareem** [datocms/middleman-dato#5]
I added this in config

```
activate :dato,
  token: 'token121212',
  base_url: 'http://mysite.com'
```

This is error I get on start

/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dato-0.3.3/lib/dato/local/json_api_entity.rb:61:in `dereference_linkage': undefined method `[]' for nil:NilClass (NoMethodError

**Comment by stefanoverna** [comment]
Thanks for the report @meandkareem, the bug was in the underlying `dato` gem. Version 0.3.5 fixes the problem:

```
bundle update dato
```
