### ISSUE TITLE
Dato content never refreshed unless server is restarted

### ISSUE THREAD

**Issue by danhalliday** [datocms/middleman-dato#6]
System:

    macOS 10.12.3
    Ruby ruby-2.4.0
    dato (0.3.11)
    middleman-dato (0.7.2)

I've also checked `DISABLE_DATO_REFRESH` is unset.

**Comment by stefanoverna** [comment]
the documentation here was a bit stale.. I've cleaned up the README pointing it to the [updated documentation](https://docs.datocms.com/middleman/overview.html).

The current way to enable content reload is the following:

```ruby
activate :dato, live_reload: true

configure :development do
  activate :livereload
end
```
