### ISSUE TITLE
Page title suffix doesn't seem to work

### ISSUE THREAD

**Issue by danhalliday** [datocms/middleman-dato#7]
If I set a title suffix in my site's SEO settings, I get a preview which looks right:

![screen shot 2017-03-22 at 17 10 20](https://cloud.githubusercontent.com/assets/1068575/24210906/7088de54-0f22-11e7-880d-164809e3898f.png)

Then I go to a page model and look at the SEO field there, and that looks right (with the title suffix appended):

![screen shot 2017-03-22 at 17 11 17](https://cloud.githubusercontent.com/assets/1068575/24210952/940db944-0f22-11e7-887f-aa62989e632e.png)

But when I build the site, the suffix is not appended:

![screen shot 2017-03-22 at 17 12 12](https://cloud.githubusercontent.com/assets/1068575/24211008/b5cc7516-0f22-11e7-82a5-f9fe87e3cfb8.png)

I'm using the standard code in the docs:

    Page template:
    <% content_for(:head) do %>
      <%= dato_meta_tags(page) %>
    <% end %>

    Head:
    <%= yield_content :head %>

**Comment by danhalliday** [comment]
I tracked this down to Dato's admin, so it's not a gem issue. The suffix is omitted if the total length of the title is too long. I didn't realise this because there's nowhere in the UI that makes that clear.

**Comment by stefanoverna** [comment]
Thanks @danhalliday, I've updated the documentation to better explain the behaviour:

https://docs.datocms.com/middleman/seo.html

**Comment by PrimozRome** [comment]
> Thanks @danhalliday, I've updated the documentation to better explain the behaviour:
> 
> https://docs.datocms.com/middleman/seo.html

Hi Sfefan, above link doesn't seem to be working...
